import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/footer/Footer";
import fixelDisplay from "@/fonts/fixelDisplay";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fixelDisplay.className}>
        <div className="flex flex-col justify-between items-center w-full min-h-screen pt-4 bg-white overflow-x-hidden">
          <div className="relative w-full">
            <div className="sticky top-4 left-0 right-0 z-100">
              <Header />
            </div>
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
