export const techStackIconsArray = [
  "icon-adobe",
  "icon-ai",
  "icon-css",
  "icon-figma",
  "icon-fraimer",
  "icon-html",
  "icon-js",
  "icon-lottie",
  "icon-nextjs",
  "icon-node",
  "icon-react",
  "icon-redux",
  "icon-tailwind",
  "icon-typescript",
  "icon-webflow",
];
